# Format checks for Nix
name: Format Nix
on:
  push:
    paths:
      - "**/*.nix"
  pull_request:
    paths:
      - "**/*.nix"
permissions:
  contents: read
jobs:
  check-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Check Nix formatting
        run: nix develop --command alejandra --check .
